// Equip Balaklava and earplugs S1-12
{s1 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s1] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s1, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s2 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s2] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s2, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s3 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s3] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s3, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s4 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s4] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s4, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s5 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s5] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s5, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s6 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s6] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s6, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s7 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s7] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s7, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s8 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s8] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s8, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s9 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s9] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s9, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s10 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s10] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s10, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s11 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s11] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s11, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
{s12 addWeapon _x} forEach ["ACE_GlassesBalaklava","ACE_Earplugs"];
[s12] execFSM "x\ace\addons\sys_goggles\use_earplug.fsm";
[s12, "ACE_GlassesBalaklava"] execFSM "x\ace\addons\sys_goggles\use_glasses.fsm";
